# Conda environment specification. The dependencies defined in this file will be
# automatically provisioned for runs against docker, VM, and HDI cluster targets.

# Details about the Conda environment file format:
# https://conda.io/docs/using/envs.html#create-environment-file-by-hand

# For Spark packages and configuration, see spark_dependencies.yml.

name: project_environment
dependencies:
  - python=3.5.2

  - pip:
    - azure-ml-api-sdk==0.1.0a9
    - Pillow==4.2.1
    - tensorflow==1.3.0
    - keras==2.0.8
    - h5py==2.7.1
